<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
    <title>Hello</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://unpkg.com/purecss@0.6.2/build/pure-min.css" integrity="sha384-UQiGfs9ICog+LwheBSRCt1o5cbyKIHbwjWscjemyBMT9YCUMZffs6UqUTd0hObXD" crossorigin="anonymous">
        <!--[if lte IE 8]>
        <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-old-ie-min.css">
        <![endif]-->
        <!--[if gt IE 8]>
        <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-min.css">
        <![endif]-->
        <style>div.pure-g div {background-color: #ebebeb;}</style>
    </head>
    <body>
        <h1>Home Controller</h1>
    <div class="pure-g">
        <div class="pure-u-8-24 pure-u-md-1"> Grid 1 </div>
        <div class="pure-u-8-24 pure-u-md-1"> Grid 2 </div>
        <div class="pure-u-8-24 pure-u-md-1"> Grid 3 </div>
    </div>
</body>
</html>
